In [1]:
import pandas as pd

In [120]:
counties_ts_df = pd.read_csv("./Data/counties.timeseries.csv")
# counties_ts_df.describe()

In [121]:
counties_ts_df.dropna(how="all",axis=1,inplace=True)
print(counties_ts_df.shape)
counties_ts_df.drop(columns=['country','locationId'],inplace=True)
counties_ts_df.info()

(2131352, 34)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2131352 entries, 0 to 2131351
Data columns (total 32 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   date                                    object
 1   state                                   object
 2   county                                  object
 3   fips                                    int64
 4   actuals.cases                           float64
 5   actuals.deaths                          float64
 6   actuals.positiveTests                   float64
 7   actuals.negativeTests                   float64
 8   actuals.contactTracers                  float64
 9   actuals.hospitalBeds.capacity           float64
 10  actuals.hospitalBeds.currentUsageTotal  float64
 11  actuals.hospitalBeds.currentUsageCovid  float64
 12  actuals.icuBeds.capacity                float64
 13  actuals.icuBeds.currentUsageTotal       float64
 14  actuals.icuBeds.currentUsageCovid       float64
 15  actuals.newCases                        float64
 16  actuals.vaccinesDistributed             float64
 17  actuals.vaccinationsInitiated           float64
 18  actuals.vaccinationsCompleted           float64
 19  metrics.testPositivityRatio             float64
 20  metrics.caseDensity                     float64
 21  metrics.contactTracerCapacityRatio      float64
 22  metrics.infectionRate                   float64
 23  metrics.infectionRateCI90               float64
 24  metrics.icuCapacityRatio                float64
 25  riskLevels.overall                      int64
 26  metrics.vaccinationsInitiatedRatio      float64
 27  metrics.vaccinationsCompletedRatio      float64
 28  actuals.newDeaths                       float64
 29  actuals.vaccinesAdministered            float64
 30  riskLevels.caseDensity                  int64
 31  cdcTransmissionLevel                    int64
dtypes: float64(25), int64(4), object(3)
memory usage: 520.3+ MB

In [122]:
final_df = counties_ts_df[["date",'fips',"state","county","actuals.cases","actuals.newCases","actuals.deaths","actuals.newDeaths","metrics.caseDensity","actuals.hospitalBeds.currentUsageTotal",
                        "actuals.hospitalBeds.currentUsageCovid","actuals.icuBeds.currentUsageTotal",
                        "actuals.icuBeds.currentUsageCovid","metrics.vaccinationsCompletedRatio", "metrics.vaccinationsInitiatedRatio", "metrics.infectionRate", 
                        "riskLevels.overall","riskLevels.caseDensity", "cdcTransmissionLevel", "metrics.testPositivityRatio"]]

Features Dropped:
1. Positive Tests (Cases metric instead)
2. Negative Tests 

Too many missing Values:
1. actuals.hospitalBeds.currentUsageTotal 1920021
2. actuals.hospitalBeds.currentUsageCovid 1979301
3. actuals.icuBeds.currentUsageTotal 2006922
4. actuals.icuBeds.currentUsageCovid 2030787

In [123]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2131352 entries, 0 to 2131351
Data columns (total 20 columns):
 #   Column                                  Dtype
---  ------                                  -----
 0   date                                    object
 1   fips                                    int64
 2   state                                   object
 3   county                                  object
 4   actuals.cases                           float64
 5   actuals.newCases                        float64
 6   actuals.deaths                          float64
 7   actuals.newDeaths                       float64
 8   metrics.caseDensity                     float64
 9   actuals.hospitalBeds.currentUsageTotal  float64
 10  actuals.hospitalBeds.currentUsageCovid  float64
 11  actuals.icuBeds.currentUsageTotal       float64
 12  actuals.icuBeds.currentUsageCovid       float64
 13  metrics.vaccinationsCompletedRatio      float64
 14  metrics.vaccinationsInitiatedRatio      float64
 15  metrics.infectionRate                   float64
 16  riskLevels.overall                      int64
 17  riskLevels.caseDensity                  int64
 18  cdcTransmissionLevel                    int64
 19  metrics.testPositivityRatio             float64
dtypes: float64(13), int64(4), object(3)
memory usage: 325.2+ MB

In [124]:
for col in final_df.columns:
    print(col, final_df[col].isna().sum())

date 0
fips 0
state 0
county 0
actuals.cases 70080
actuals.newCases 90247
actuals.deaths 89357
actuals.newDeaths 99607
metrics.caseDensity 50092
actuals.hospitalBeds.currentUsageTotal 1920021
actuals.hospitalBeds.currentUsageCovid 1979301
actuals.icuBeds.currentUsageTotal 2006922
actuals.icuBeds.currentUsageCovid 2030787
metrics.vaccinationsCompletedRatio 1094528
metrics.vaccinationsInitiatedRatio 1082319
metrics.infectionRate 195903
riskLevels.overall 0
riskLevels.caseDensity 0
cdcTransmissionLevel 0
metrics.testPositivityRatio 142448

In [125]:
final_df = final_df[["date",'fips',"state","county","actuals.cases","actuals.newCases","actuals.deaths","actuals.newDeaths","metrics.caseDensity", "metrics.vaccinationsCompletedRatio", "metrics.vaccinationsInitiatedRatio", "metrics.infectionRate", 
                        "riskLevels.overall","riskLevels.caseDensity", "cdcTransmissionLevel", "metrics.testPositivityRatio"]]
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2131352 entries, 0 to 2131351
Data columns (total 16 columns):
 #   Column                              Dtype
---  ------                              -----
 0   date                                object
 1   fips                                int64
 2   state                               object
 3   county                              object
 4   actuals.cases                       float64
 5   actuals.newCases                    float64
 6   actuals.deaths                      float64
 7   actuals.newDeaths                   float64
 8   metrics.caseDensity                 float64
 9   metrics.vaccinationsCompletedRatio  float64
 10  metrics.vaccinationsInitiatedRatio  float64
 11  metrics.infectionRate               float64
 12  riskLevels.overall                  int64
 13  riskLevels.caseDensity              int64
 14  cdcTransmissionLevel                int64
 15  metrics.testPositivityRatio         float64
dtypes: float64(9), int64(4), object(3)
memory usage: 260.2+ MB

In [126]:
for col in final_df.columns:
    print(col, final_df[col].isna().sum())

date 0
fips 0
state 0
county 0
actuals.cases 70080
actuals.newCases 90247
actuals.deaths 89357
actuals.newDeaths 99607
metrics.caseDensity 50092
metrics.vaccinationsCompletedRatio 1094528
metrics.vaccinationsInitiatedRatio 1082319
metrics.infectionRate 195903
riskLevels.overall 0
riskLevels.caseDensity 0
cdcTransmissionLevel 0
metrics.testPositivityRatio 142448

## Steps Ahead
nearest_state = num_passengers.interpolate(method='nearest',limit_direction='forward', axis=0)

1. Split this by county
2. Create DataTimeIndex for each county
3. Interpolate within county for required features

4. Repeating data qc for states
5. For each county, combine it's respective states features.
6. Add county population and State population as features as well. Create a combined data frame With all combined features

7. Depending on window size - Take Mean, Std Dev for that window and add those features to main dataframe (Total 90 features)
8. Aggregate all the 90 features across different counties for each time point.
9. Clean up this final data frame - Remove Redundnant feautures, Features with majority empty cells
10. Transform final DataFrame - Convert features to a range (for categorical features), perform normalization on final features

For Later:
1. County Correlation 
2. Different time splits
3. Use State level hospital information

In [127]:
final_df.to_csv("counties.finalfeatures.timeseries.csv",index=False)

In [128]:
final_df

,date,fips,state,county,actuals.cases,actuals.newCases,actuals.deaths,actuals.newDeaths,metrics.caseDensity,metrics.vaccinationsCompletedRatio,metrics.vaccinationsInitiatedRatio,metrics.infectionRate,riskLevels.overall,riskLevels.caseDensity,cdcTransmissionLevel,metrics.testPositivityRatio
0,2020-04-09,2013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
1,2020-04-10,2013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
2,2020-04-11,2013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
3,2020-04-12,2013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
4,2020-04-13,2013,AK,Aleutians East Borough,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2131347,2022-01-07,56045,WY,Weston County,1263.0,2.0,16.0,0.0,17.0,0.347,0.389,1.13,2,2,3,0.087
2131348,2022-01-08,56045,WY,Weston County,1263.0,0.0,16.0,0.0,18.9,0.349,0.390,1.15,2,2,3,NaN
2131349,2022-01-09,56045,WY,Weston County,1263.0,0.0,16.0,0.0,20.8,0.349,0.390,1.17,2,2,3,NaN
2131350,2022-01-10,56045,WY,Weston County,1268.0,5.0,16.0,0.0,22.7,0.349,0.390,1.19,2,2,3,NaN
2131351,2022-01-11,56045,WY,Weston County,1275.0,7.0,16.0,0.0,34.0,0.350,0.391,1.21,3,3,3,NaN

In [44]:
states_ts_df = pd.read_csv("./Data/states.timeseries.csv")
states_ts_df.dropna(how="all",axis=1,inplace=True)
states_ts_df.drop(columns=['country','fips','locationId'],inplace=True)
states_ts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36322 entries, 0 to 36321
Data columns (total 30 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   date                                    36322 non-null  object
 1   state                                   36322 non-null  object
 2   actuals.cases                           35389 non-null  float64
 3   actuals.deaths                          36076 non-null  float64
 4   actuals.positiveTests                   35473 non-null  float64
 5   actuals.negativeTests                   35714 non-null  float64
 6   actuals.contactTracers                  31198 non-null  float64
 7   actuals.hospitalBeds.capacity           25419 non-null  float64
 8   actuals.hospitalBeds.currentUsageTotal  25419 non-null  float64
 9   actuals.hospitalBeds.currentUsageCovid  25419 non-null  float64
 10  actuals.icuBeds.capacity                25419 non-null  float64
 11  actuals.icuBeds.currentUsageTotal       25419 non-null  float64
 12  actuals.icuBeds.currentUsageCovid       25419 non-null  float64
 13  actuals.newCases                        35165 non-null  float64
 14  actuals.vaccinesDistributed             16126 non-null  float64
 15  actuals.vaccinationsInitiated           16126 non-null  float64
 16  actuals.vaccinationsCompleted           16126 non-null  float64
 17  metrics.testPositivityRatio             35490 non-null  float64
 18  metrics.caseDensity                     35400 non-null  float64
 19  metrics.contactTracerCapacityRatio      30341 non-null  float64
 20  metrics.infectionRate                   34623 non-null  float64
 21  metrics.infectionRateCI90               34623 non-null  float64
 22  metrics.icuCapacityRatio                25419 non-null  float64
 23  riskLevels.overall                      36322 non-null  int64
 24  metrics.vaccinationsInitiatedRatio      16126 non-null  float64
 25  metrics.vaccinationsCompletedRatio      16126 non-null  float64
 26  actuals.newDeaths                       35761 non-null  float64
 27  actuals.vaccinesAdministered            16126 non-null  float64
 28  riskLevels.caseDensity                  36322 non-null  int64
 29  cdcTransmissionLevel                    36322 non-null  int64
dtypes: float64(25), int64(3), object(2)
memory usage: 8.3+ MB

In [47]:
states_final_df = states_ts_df[["date","state","actuals.cases","actuals.newCases","actuals.deaths","actuals.newDeaths","metrics.caseDensity","actuals.hospitalBeds.currentUsageTotal",
                        "actuals.hospitalBeds.currentUsageCovid","actuals.icuBeds.currentUsageTotal",
                        "actuals.icuBeds.currentUsageCovid","metrics.vaccinationsCompletedRatio", "metrics.vaccinationsInitiatedRatio", "metrics.infectionRate", 
                        "riskLevels.overall","riskLevels.caseDensity", "cdcTransmissionLevel", "metrics.testPositivityRatio"]]
states_final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36322 entries, 0 to 36321
Data columns (total 18 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   date                                    36322 non-null  object
 1   state                                   36322 non-null  object
 2   actuals.cases                           35389 non-null  float64
 3   actuals.newCases                        35165 non-null  float64
 4   actuals.deaths                          36076 non-null  float64
 5   actuals.newDeaths                       35761 non-null  float64
 6   metrics.caseDensity                     35400 non-null  float64
 7   actuals.hospitalBeds.currentUsageTotal  25419 non-null  float64
 8   actuals.hospitalBeds.currentUsageCovid  25419 non-null  float64
 9   actuals.icuBeds.currentUsageTotal       25419 non-null  float64
 10  actuals.icuBeds.currentUsageCovid       25419 non-null  float64
 11  metrics.vaccinationsCompletedRatio      16126 non-null  float64
 12  metrics.vaccinationsInitiatedRatio      16126 non-null  float64
 13  metrics.infectionRate                   34623 non-null  float64
 14  riskLevels.overall                      36322 non-null  int64
 15  riskLevels.caseDensity                  36322 non-null  int64
 16  cdcTransmissionLevel                    36322 non-null  int64
 17  metrics.testPositivityRatio             35490 non-null  float64
dtypes: float64(13), int64(3), object(2)
memory usage: 5.0+ MB

In [48]:
#Removing Hospital Data for now
states_final_df = states_final_df[["date","state","actuals.cases","actuals.newCases","actuals.deaths","actuals.newDeaths","metrics.caseDensity", "metrics.vaccinationsCompletedRatio", "metrics.vaccinationsInitiatedRatio", "metrics.infectionRate", 
                        "riskLevels.overall","riskLevels.caseDensity", "cdcTransmissionLevel", "metrics.testPositivityRatio"]]
states_final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36322 entries, 0 to 36321
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   date                                36322 non-null  object
 1   state                               36322 non-null  object
 2   actuals.cases                       35389 non-null  float64
 3   actuals.newCases                    35165 non-null  float64
 4   actuals.deaths                      36076 non-null  float64
 5   actuals.newDeaths                   35761 non-null  float64
 6   metrics.caseDensity                 35400 non-null  float64
 7   metrics.vaccinationsCompletedRatio  16126 non-null  float64
 8   metrics.vaccinationsInitiatedRatio  16126 non-null  float64
 9   metrics.infectionRate               34623 non-null  float64
 10  riskLevels.overall                  36322 non-null  int64
 11  riskLevels.caseDensity              36322 non-null  int64
 12  cdcTransmissionLevel                36322 non-null  int64
 13  metrics.testPositivityRatio         35490 non-null  float64
dtypes: float64(9), int64(3), object(2)
memory usage: 3.9+ MB

In [49]:
states_final_df

,date,state,actuals.cases,actuals.newCases,actuals.deaths,actuals.newDeaths,metrics.caseDensity,metrics.vaccinationsCompletedRatio,metrics.vaccinationsInitiatedRatio,metrics.infectionRate,riskLevels.overall,riskLevels.caseDensity,cdcTransmissionLevel,metrics.testPositivityRatio
0,2020-03-01,AK,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
1,2020-03-02,AK,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
2,2020-03-03,AK,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
3,2020-03-04,AK,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
4,2020-03-05,AK,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36317,2022-01-08,WY,119857.0,0.0,1572.0,0.0,105.4,0.479,0.564,1.53,5,5,3,0.199
36318,2022-01-09,WY,119857.0,0.0,1572.0,0.0,112.9,0.479,0.564,1.52,5,5,3,0.199
36319,2022-01-10,WY,121519.0,1662.0,1572.0,0.0,120.4,0.479,0.564,1.52,5,5,3,NaN
36320,2022-01-11,WY,122754.0,1235.0,1588.0,16.0,132.4,0.480,0.565,1.51,5,5,3,NaN
36321,2022-01-12,WY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,5,3,NaN

In [50]:
states_final_df.to_csv("states.finalfeatures.timeseries.csv",index=False)

## Creating Final Combined Dataframe

### Combining Population Data

In [112]:
cleaned_states_df = pd.read_csv("states.finalfeatures.timeseries.csv")
cleaned_states_df.shape

(36322, 14)

In [114]:
states_info_df = pd.read_csv("./Data/states.csv")
state_pop_df = states_info_df[["state","population"]]
state_pop_df.set_index("state",inplace=True)

population_list = []
for col in cleaned_states_df["state"]:
    population = state_pop_df.loc[col]["population"]
    population_list.append(population)
    
cleaned_states_df["population"] = population_list
cleaned_states_df.shape

(36322, 15)

In [119]:
cleaned_counties_df = pd.read_csv("counties.finalfeatures.timeseries.csv")
counties_info_df = pd.read_csv("./Data/counties.csv")
counties_pop_df = counties_info_df[["county","population"]]
counties_pop_df.set_index("county",inplace=True)
cleaned_counties_df['vaccinationsCompletedRatio.Density'] = cleaned_counties_df["metrics.vaccinationsCompletedRatio"]/counties_pop_df.loc[county]["population"]
cleaned_counties_df.shape

(2131352, 15)

In [118]:
counties_info_df = pd.read_csv("./Data/counties.csv")
counties_pop_df = counties_info_df[["county","population"]]
counties_pop_df.set_index("county",inplace=True)
cleaned_counties_df['vaccinationsCompletedRatio.Density'] = cleaned_counties_df["metrics.vaccinationsCompletedRatio"]/counties_pop_df.loc[county]["population"]


population_list = []
pop_based_features = ["metrics.vaccinationsCompletedRatio","metrics.vaccinationsInitiatedRatio","actuals.deaths"]
for col in cleaned_counties_df["county"]:
    population = counties_pop_df.loc[col]["population"]
    population_list.append(population)
    
cleaned_counties_df["population"] = population_list
cleaned_counties_df.shape

(2131352, 16)

In [ ]:
# def create_pop_based_features():

cleaned_counties_df['vaccinationsCompletedRatio.Density'] = cleaned_counties_df["metrics.vaccinationsCompletedRatio"]/counties_pop_df.loc[county]["population"]
    
cleaned_counties_df['vaccinationsCompletedRatio.Density'] = items_df['Actual Price'] - \
    ((items_df['Discount(%)']/100) * items_df['Actual Price'])

In [ ]:
cleaned_counties_df = pd.read_csv("counties.finalfeatures.timeseries.csv")
states_final_df.to_csv("states.finalfeatures.timeseries.csv",index=False)

In [96]:
# final_states_df = pd.merge(cleaned_states_df, state_pop_df, on="state")
# final_counties_df = pd.merge(cleaned_counties_df, counties_pop_df, how='inner',on="county")

In [97]:
final_counties_df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9699748 entries, 0 to 9699747
Data columns (total 16 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   date                                9699748 non-null  object
 1   state                               9699748 non-null  object
 2   county                              9699748 non-null  object
 3   actuals.cases                       9386898 non-null  float64
 4   actuals.newCases                    9302622 non-null  float64
 5   actuals.deaths                      9475736 non-null  float64
 6   actuals.newDeaths                   9429960 non-null  float64
 7   metrics.caseDensity                 9473061 non-null  float64
 8   metrics.vaccinationsCompletedRatio  4750239 non-null  float64
 9   metrics.vaccinationsInitiatedRatio  4807720 non-null  float64
 10  metrics.infectionRate               8963232 non-null  float64
 11  riskLevels.overall                  9699748 non-null  int64
 12  riskLevels.caseDensity              9699748 non-null  int64
 13  cdcTransmissionLevel                9699748 non-null  int64
 14  metrics.testPositivityRatio         9269036 non-null  float64
 15  population                          9699748 non-null  int64
dtypes: float64(9), int64(4), object(3)
memory usage: 1.2+ GB

In [98]:
#cleaned_counties_df.info(verbose=True,show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2131352 entries, 0 to 2131351
Data columns (total 15 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   date                                2131352 non-null  object
 1   state                               2131352 non-null  object
 2   county                              2131352 non-null  object
 3   actuals.cases                       2061272 non-null  float64
 4   actuals.newCases                    2041105 non-null  float64
 5   actuals.deaths                      2041995 non-null  float64
 6   actuals.newDeaths                   2031745 non-null  float64
 7   metrics.caseDensity                 2081260 non-null  float64
 8   metrics.vaccinationsCompletedRatio  1036824 non-null  float64
 9   metrics.vaccinationsInitiatedRatio  1049033 non-null  float64
 10  metrics.infectionRate               1935449 non-null  float64
 11  riskLevels.overall                  2131352 non-null  int64
 12  riskLevels.caseDensity              2131352 non-null  int64
 13  cdcTransmissionLevel                2131352 non-null  int64
 14  metrics.testPositivityRatio         1988904 non-null  float64
dtypes: float64(9), int64(3), object(3)
memory usage: 243.9+ MB

In [137]:
temp_df = final_df[final_df['fips'] == 41001]
temp_df.head(40).tail(2

,date,fips,state,county,actuals.cases,actuals.newCases,actuals.deaths,actuals.newDeaths,metrics.caseDensity,metrics.vaccinationsCompletedRatio,metrics.vaccinationsInitiatedRatio,metrics.infectionRate,riskLevels.overall,riskLevels.caseDensity,cdcTransmissionLevel,metrics.testPositivityRatio
1464383,2020-05-12,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.045
1464384,2020-05-13,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464385,2020-05-14,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464386,2020-05-15,41001,OR,Baker County,3.0,2.0,0.0,0.0,1.8,NaN,NaN,1.0,1,1,1,0.000
1464387,2020-05-16,41001,OR,Baker County,1.0,NaN,0.0,0.0,NaN,NaN,NaN,1.0,1,1,1,0.000
1464388,2020-05-17,41001,OR,Baker County,1.0,0.0,0.0,0.0,2.1,NaN,NaN,1.0,1,1,1,0.000
1464389,2020-05-18,41001,OR,Baker County,1.0,0.0,0.0,0.0,2.1,NaN,NaN,1.0,1,1,1,0.000
1464390,2020-05-19,41001,OR,Baker County,1.0,0.0,0.0,0.0,2.1,NaN,NaN,1.0,1,1,1,0.000
1464391,2020-05-20,41001,OR,Baker County,1.0,0.0,0.0,0.0,2.1,NaN,NaN,1.0,1,1,1,0.000
1464392,2020-05-21,41001,OR,Baker County,1.0,0.0,0.0,0.0,2.1,NaN,NaN,1.0,1,1,1,0.000
1464393,2020-05-22,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464394,2020-05-23,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464395,2020-05-24,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464396,2020-05-25,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464397,2020-05-26,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464398,2020-05-27,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464399,2020-05-28,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464400,2020-05-29,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464401,2020-05-30,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000
1464402,2020-05-31,41001,OR,Baker County,1.0,0.0,0.0,0.0,0.0,NaN,NaN,1.0,0,0,0,0.000